#!/usr/bin/env bash
# =============================================================================
# Write /etc/nginx/snippets/cloudflare-realip.conf from Cloudflare's published
# address lists, so that behind the orange cloud nginx takes the visitor's IP
# from CF-Connecting-IP (and only when the request really came from Cloudflare).
# The API's per-address rate limit depends on it. Harmless when the DNS record
# is grey (DNS only): then no request comes from those ranges.
#
# Run by provision.sh; re-run now and then (Cloudflare rarely changes the lists).
# =============================================================================
set -euo pipefail

OUT="${OUT:-/etc/nginx/snippets/cloudflare-realip.conf}"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Generated by deploy/lightsail/cloudflare-realip.sh on $(date -u +%F). Do not edit."
  for list in ips-v4 ips-v6; do
    curl -fsS --max-time 20 "https://www.cloudflare.com/$list" | while read -r cidr; do
      [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
    done
  done
  echo "real_ip_header CF-Connecting-IP;"
} > "$tmp"

# A failed or empty download must not replace a working file.
if [ "$(grep -c '^set_real_ip_from' "$tmp")" -lt 10 ]; then
  echo "!!  Cloudflare's lists came back short; kept the existing $OUT"
  exit 1
fi
sudo mkdir -p "$(dirname "$OUT")"
sudo install -m 644 "$tmp" "$OUT"
echo "    wrote $OUT ($(grep -c '^set_real_ip_from' "$OUT") ranges)"
